# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DouYuZB' do
pod 'Alamofire', '~> 4.2.0'

  # Pods for DouYuZB

  target 'DouYuZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYuZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
